apiVersion: v1
kind: PersistentVolume
metadata:
  name: speedtest-claim0
  labels:
    type: local
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/speedtest-claim0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: speedtest-claim0
  name: speedtest-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: speedtest
  name: speedtest
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 80
  selector:
    app: speedtest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: speedtest
  name: speedtest
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - image: toronz/speedtest:latest
        command: ["/bin/bash", "-c"]
        args: ["mkdir -p /var/www/html && ln -s /var/www/html /var/www/html/speedtest; curl https://raw.githubusercontent.com/ToroNZ/speedtest/docker/example-gauges.html -o /var/www/html/index.html && curl https://raw.githubusercontent.com
/ToroNZ/speedtest/docker/getIP.php -o /var/www/html/getIP.php && curl https://raw.githubusercontent.com/ToroNZ/speedtest/docker/empty.php -o /var/www/html/empty.php && curl https://raw.githubusercontent.com/ToroNZ/speedtest/docker/garbage.
php -o /var/www/html/garbage.php && curl https://raw.githubusercontent.com/ToroNZ/speedtest/docker/speedtest_worker.min.js -o /var/www/html/speedtest_worker.min.js; /usr/local/bin/apache2-foreground"]
        name: speedtest
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: speedtest-claim0
      restartPolicy: Always
      volumes:
      - name: speedtest-claim0
        persistentVolumeClaim:
          claimName: speedtest-claim0
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: speedtest
  namespace: default
spec:
  rules:
  - host: speedtest.k8s.evilcloud.xyz
    http:
      paths:
      - backend:
          serviceName: speedtest
          servicePort: 8888
        path: /
